# Generated by Django 5.0.2 on 2024-02-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='change_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='дата и время редактирования'),
        ),
        migrations.AlterField(
            model_name='post',
            name='change_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='дата и время редактирования'),
        ),
    ]
