# Generated by Django 5.0.2 on 2024-02-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='change_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата редактирования'),
        ),
    ]
