# Generated by Django 5.0.2 on 2024-02-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='change_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='дата редактирования'),
        ),
    ]
